// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8N96twEv7YmNEMHmCQEISSjVYnHXBu3M',
    appId: '1:746332115602:web:4f29438eb1d67c25b54c4b',
    messagingSenderId: '746332115602',
    projectId: 'cldcflutter',
    authDomain: 'cldcflutter.firebaseapp.com',
    storageBucket: 'cldcflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3BCfwZTkZnv_BP78qFBN0EvK5vuyKfG8',
    appId: '1:746332115602:android:8a41de5d3ba5c9e9b54c4b',
    messagingSenderId: '746332115602',
    projectId: 'cldcflutter',
    storageBucket: 'cldcflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVKEX29X5AURUqLHkYmAEOmfqPYMsUw4A',
    appId: '1:746332115602:ios:75eabd2d276816dab54c4b',
    messagingSenderId: '746332115602',
    projectId: 'cldcflutter',
    storageBucket: 'cldcflutter.appspot.com',
    iosClientId: '746332115602-b6foaorle2467c9u7hfd340gf8apmcgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVKEX29X5AURUqLHkYmAEOmfqPYMsUw4A',
    appId: '1:746332115602:ios:75eabd2d276816dab54c4b',
    messagingSenderId: '746332115602',
    projectId: 'cldcflutter',
    storageBucket: 'cldcflutter.appspot.com',
    iosClientId: '746332115602-b6foaorle2467c9u7hfd340gf8apmcgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApplication',
  );
}
